source 'http://rubygems.org'

#gem 'devise'
gem 'authlogic', :git => 'http://github.com/binarylogic/authlogic.git'
gem 'authlogic_wind'
gem 'hydra-head', '3.1.0'
gem "rails", '~> 3.0.10'
gem "blacklight", '3.0.0'  
gem "active-fedora", '~>3.1.1'
gem 'builder'
gem 'columnize'
gem 'crack'
gem 'cul_image_props'
gem 'cul_scv_hydra'
gem 'curb'
gem 'database_cleaner'
gem 'declarative_authorization'
gem 'diff-lcs'
gem 'facets', '~> 2'
gem 'haml'
gem 'httpclient', '2.1.6.1'
gem 'httparty'
gem 'json_pure', '>1.4.3'
gem 'launchy'
gem 'linecache'
gem 'mime-types'
gem 'multipart-post'
gem 'mysql'
gem 'mysql2', '~> 0.2'
gem 'net-ldap', '>=0.1.1'
gem 'nokogiri' # Default to using the version required by Blacklight
gem 'om', '>=1.4.0'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'rcov'
gem 'rsolr' # Default to using the version required by Blacklight
gem 'rsolr-ext' # Default to using the version required by Blacklight
gem 'ruby-prof'
gem 'rubydora'
gem 'RedCloth', '=4.2.3'
gem 'sass'
gem 'solr-ruby' 
gem 'mediashelf-loggable', '>=0.4.7' ##This can be removed once this dependency is declared in solrizer
gem 'solrizer', '>=1.1.0'
gem 'solrizer-fedora', '>=1.1.0'
gem 'term-ansicolor'
gem 'trollop'
# gem 'will_paginate'
gem 'xml-simple'
gem 'block_helpers'
gem 'sanitize'
group :development do
  gem 'yard'
  gem 'jettywrapper', "~> 0.0.10"
  gem 'ruby-debug'
  gem 'ruby-debug-base'
  gem 'rspec', '>= 2.0.0'  
  gem 'rspec-rails', '>= 2.0.0' # rspec-rails 2.0.0 requires Rails 3.
  gem 'rest-client'
  gem 'mocha'
  gem 'cucumber', '>=0.8.5'
  gem 'cucumber-rails', '>=1.0.0'
  gem 'gherkin'
  gem 'factory_girl'
  gem "rake"
end
